/* Prairie View Dental — knowledge base and widget configuration.
 * A site owner embeds the widget by writing their own config like this one
 * and passing it to ChatWidget.init(). Phrases are matched against the
 * normalized user message; keywords are weighted per token.
 */
window.PVD_CONFIG = {
  businessName: "Prairie View Dental",
  primaryColor: "#0e6b5c",
  phone: "(402) 555-0188",
  email: "hello@prairieviewdental.example",
  greeting: "Hi! I'm the Prairie View Dental helper. Ask me about hours, services, pricing, insurance, or booking a visit.",
  starterChips: ["What are your hours?", "What services do you offer?", "Do you take insurance?"],
  intents: [
    { id: "hours", label: "office hours", chip: "What are your hours?",
      keywords: { hour: 3, open: 3, close: 3, time: 2 },
      phrases: ["what are your hours", "when are you open", "when do you open", "when do you close", "office hours"],
      answer: "We're open <strong>Monday–Thursday 8:00 AM–5:00 PM</strong> and <strong>Friday 8:00 AM–2:00 PM</strong>. We're closed Saturday and Sunday.",
      chips: ["Are you open Saturday?", "How do I book a visit?"] },
    { id: "weekend-hours", label: "weekend hours", chip: "Are you open on weekends?",
      keywords: { saturday: 4, sunday: 4, weekend: 4, sat: 3, sun: 3 },
      phrases: ["open saturday", "open sunday", "open on weekends", "open weekends"],
      answer: "We're closed on Saturdays and Sundays. On Fridays we're here until 2:00 PM if you need a weekday slot.",
      chips: ["What are your hours?", "How do I book a visit?"] },
    { id: "location", label: "location and directions", chip: "Where are you located?",
      keywords: { where: 3, located: 4, location: 4, address: 4, direction: 3, find: 2 },
      phrases: ["where are you", "where are you located", "what is your address"],
      answer: "You'll find us at <strong>2901 Pine Lake Rd, Suite 120, Lincoln, NE 68516</strong> — just off the Pine Lake interchange.",
      chips: ["Where do I park?", "What are your hours?"] },
    { id: "parking", label: "parking", chip: "Where do I park?",
      keywords: { park: 5, parking: 5, lot: 2 },
      phrases: ["where do i park", "is there parking"],
      answer: "There's a free patient lot right behind the building, with the entrance on Pine Lake Rd.",
      chips: ["Where are you located?"] },
    { id: "new-patients", label: "new patients", chip: "Do you take new patients?",
      keywords: { new: 2, patient: 3, first: 2 },
      phrases: ["new patient", "new patients", "first visit", "accepting new"],
      answer: "Yes, we love new patients! Our <strong>$99 new-patient special</strong> includes a full exam, cleaning, and x-rays.",
      chips: ["How do I book a visit?", "Do you take insurance?"] },
    { id: "insurance", label: "insurance", chip: "Do you take insurance?",
      keywords: { insurance: 5, delta: 3, cigna: 3, aetna: 3, metlife: 3, cover: 2, coverage: 3, insure: 4 },
      phrases: ["do you take insurance", "take my insurance", "in network", "do you accept", "delta dental"],
      answer: "We're in-network with <strong>Delta Dental, Cigna, Aetna, and MetLife</strong>, and we work with most other PPO plans. We'll verify your benefits before any treatment.",
      chips: ["How much is a cleaning?", "Do you offer payment plans?"] },
    { id: "pricing", label: "pricing", chip: "How much does a cleaning cost?",
      keywords: { price: 3, cost: 3, much: 2, charge: 3, fee: 2, expensive: 2 },
      phrases: ["how much", "what does it cost", "what do you charge"],
      answer: "A routine cleaning is <strong>$120</strong>, fillings run <strong>$180–$320</strong>, and crowns <strong>$950–$1,300</strong>. Every treatment plan comes with a written estimate first — no surprises.",
      chips: ["How much is whitening?", "Do you take insurance?"] },
    { id: "whitening", label: "teeth whitening", chip: "How much is whitening?",
      keywords: { whiten: 5, whitening: 5, bleach: 4, brighten: 3, whiter: 3, teeth: 2 },
      phrases: ["teeth whitening", "how much is whitening", "whiten my teeth"],
      answer: "In-office whitening is <strong>$399</strong> (about an hour, up to 8 shades brighter). Take-home kits are <strong>$149</strong>.",
      chips: ["What services do you offer?", "How do I book a visit?"] },
    { id: "services", label: "services", chip: "What services do you offer?",
      keywords: { service: 3, offer: 2, treat: 3, procedure: 3, treatment: 2 },
      phrases: ["what services", "what do you offer", "what do you do"],
      answer: "We do cleanings and exams, tooth-colored fillings, crowns, whitening, Invisalign, implants, root canals, and emergency care — all under one roof.",
      chips: ["Do you do implants?", "How much is whitening?"] },
    { id: "implants", label: "dental implants", chip: "Do you do implants?",
      keywords: { implant: 5 },
      phrases: ["dental implants", "do you do implants", "tooth implant"],
      answer: "Yes — we place 3D-guided implants start to finish, and the consultation is free.",
      chips: ["How do I book a visit?", "Do you take insurance?"] },
    { id: "invisalign", label: "Invisalign and braces", chip: "Do you offer Invisalign?",
      keywords: { invisalign: 5, brace: 4, orthodont: 4, aligner: 4, straighten: 3, straight: 2 },
      phrases: ["do you offer invisalign", "clear aligners", "straighten my teeth"],
      answer: "We're a certified Invisalign provider. The smile assessment is free, and most treatments run 6–12 months.",
      chips: ["How do I book a visit?", "Do you offer payment plans?"] },
    { id: "emergency", label: "dental emergencies", chip: "I have a toothache, what should I do?",
      keywords: { emergency: 5, urgent: 4, pain: 3, hurt: 3, broken: 2, chipped: 2, toothache: 5, knocked: 3, swelling: 3, abscess: 4 },
      phrases: ["tooth hurts", "dental emergency", "toothache", "broke my tooth", "chipped my tooth"],
      answer: "Don't wait — we hold <strong>same-day emergency slots</strong> every weekday. Call <strong>(402) 555-0188</strong> now and we'll get you in today.",
      chips: ["What are your hours?"] },
    { id: "booking", label: "booking a visit", chip: "How do I book a visit?",
      keywords: { book: 4, appointment: 4, schedule: 4, reserve: 3 },
      phrases: ["book a visit", "book an appointment", "make an appointment", "schedule an appointment", "schedule a visit"],
      answer: "Easy — call <strong>(402) 555-0188</strong> or email <strong>hello@prairieviewdental.example</strong> and we'll find a time that works. New patients usually get in within a week.",
      chips: ["Do you take new patients?", "What are your hours?"] },
    { id: "kids", label: "kids dentistry", chip: "Do you see kids?",
      keywords: { kid: 4, child: 4, children: 4, pediatric: 4, family: 2, toddler: 3 },
      phrases: ["see kids", "see children", "do you treat children", "family dentist"],
      answer: "Absolutely — we see kids <strong>ages 3 and up</strong>, and first visits are all about making it fun, not scary.",
      chips: ["Do you take new patients?", "How do I book a visit?"] },
    { id: "anxiety", label: "anxiety and sedation", chip: "I'm nervous about dentists, what are my options?",
      keywords: { anxiety: 4, anxious: 4, nervous: 4, scared: 4, fear: 3, sedation: 5, nitrous: 4, comfort: 2, phobia: 4 },
      phrases: ["dental anxiety", "scared of the dentist", "nervous about", "do you offer sedation"],
      answer: "You're not alone — we offer <strong>nitrous oxide</strong>, noise-cancelling headphones, and a go-at-your-pace approach. Tell us you're anxious when you book and we'll plan around it.",
      chips: ["How do I book a visit?"] },
    { id: "cleaning-length", label: "cleaning length", chip: "How long does a cleaning take?",
      keywords: { long: 2 },
      phrases: ["how long does a cleaning take", "how long is a cleaning", "how long does a checkup take"],
      answer: "A routine cleaning and exam takes about <strong>45–60 minutes</strong>. First visits run a little longer since we do a full health history.",
      chips: ["How do I book a visit?"] },
    { id: "cancellation", label: "cancellation policy", chip: "What is your cancellation policy?",
      keywords: { cancel: 5, reschedule: 4, notice: 2, policy: 2, miss: 2 },
      phrases: ["cancel an appointment", "cancellation policy", "need to reschedule"],
      answer: "Life happens — just give us <strong>24 hours' notice</strong> to cancel or reschedule and there's no fee.",
      chips: ["How do I book a visit?"] },
    { id: "payment", label: "payment options", chip: "Do you offer payment plans?",
      keywords: { pay: 3, payment: 4, credit: 3, card: 2, cash: 3, carecredit: 5, financing: 4, plan: 2 },
      phrases: ["payment options", "do you offer financing", "payment plans", "how can i pay"],
      answer: "We take cash, all major cards, and offer <strong>CareCredit</strong> 0%-interest plans for bigger treatments.",
      chips: ["Do you take insurance?", "How much does a cleaning cost?"] },
    { id: "second-opinion", label: "second opinions", chip: "Do you give second opinions?",
      keywords: { second: 3, opinion: 4 },
      phrases: ["second opinion"],
      answer: "Yes — second opinions are <strong>free</strong>. Bring your x-rays (or we'll take new ones) and we'll give you a straight answer.",
      chips: ["How do I book a visit?"] }
  ]
};
